#!python

'''
Created on 23-08-2011

@author: arkus
'''

import argparse, os

from bumblepyy.service import BumblePyyService

def run(args):
    object = BumblePyyService(args.config)
    object.run()


class PidContext():
    def __init__(self, path):
        self.path = path
    def __enter__(self):
        with open(self.path, "w") as f:
            f.write(str(os.getpid()))
    def __exit__(self, *_exc):
        os.unlink(self.path)
        

if __name__ == '__main__':

    parser = argparse.ArgumentParser(description="Run Bumblepyy service")
    parser.add_argument("--config", "-c", type=str, help="Config file to use", default="/etc/bumblepyy.conf")
    parser.add_argument("--pid_file", "-p", type=str, help="Pid file to use", default="/var/run/bumblepyy.pid")
    parser.add_argument("--background", "-b", help="Run service in background", default=False, action="store_true")

    args=parser.parse_args()
    if args.background:
        import daemon

        context = daemon.DaemonContext(
            pidfile=PidContext(args.pid_file),
            #stdout = sys.stdout,
            #stderr = sys.stderr
        )
        with context:
            run(args)
    else:
        run(args)


